name: hive_timers_api
description: A Dart implementation of the TimersApi which uses Hive database.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive: ^2.2.3
  timers_api:
    path: ../timers_api

dev_dependencies:
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
