name: quick_timer
description: A simple timer app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  audioplayers: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  hive_timers_api:
    path: packages/hive_timers_api
  intl: ^0.17.0
  timers_repository:
    path: packages/timers_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  mockingjay: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
