name: timers_api
description: An abstract class and models for an API providing access to timers.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  coverage: ^1.6.1
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
